name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  pod-lint:
    name: Pod Lint
    runs-on: macOS-11
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Lint Podspec
        run: bundle exec pod lib lint --verbose --fail-fast
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build
        run: xcrun xcodebuild -project XCTest.xcodeproj -scheme XCTest
