name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  pod-lint:
    name: Pod Lint
    runs-on: macOS-15
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Bundle Install
        run: bundle install
      - name: Lint Podspec
        run: bundle exec pod lib lint --verbose --fail-fast
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Build
        run: xcrun xcodebuild -project XCTest.xcodeproj -scheme XCTest
